// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylcjlzlchinijvyojdbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsY2psemxjaGluaWp2eW9qZGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxMDM0NjEsImV4cCI6MjA4ODY3OTQ2MX0.rPK3w7Yb85MaKACLC0wbthM_YGmE_QoWa62B89Iwfr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});